esprit_mouldi:
    resource: "@EspritMouldiBundle/Resources/config/routing.yml"
    prefix:   /

daw:
    resource: "@DawBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
